### ISSUE TITLE
Is a binary available?

### ISSUE THREAD

**Issue by cmaynard** [Gabriel439/bench#1]
For those of us who don't want to install the Haskell toolchain, would you consider distributing bench as a self-contained binary? I'm using a MacBook Pro and OS X 10.11.

**Comment by Gabriel439** [comment]
Here you go: https://github.com/Gabriel439/bench/releases/tag/1.0.1

**Comment by cmaynard** [comment]
Just got back from vacation. Thanks for posting this!

**Comment by Gabriel439** [comment]
You're welcome! :)
