### ISSUE TITLE
Windows binary

### ISSUE THREAD

**Issue by sergeevabc** [Gabriel439/bench#10]
Dear Gabriel,
Could you be so kind to generate ```.exe``` for the rest of us who are merely users w/o compiler?

**Comment by sergeevabc** [comment]
Err… Hello?

**Comment by Gabriel439** [comment]
I uploaded a Windows binary for the 1.0.2 release here: https://github.com/Gabriel439/bench/releases/tag/1.0.2

**Comment by sergeevabc** [comment]
Thank you, Gabriel. Wow, it takes 16 MiB of space, a pretty heavy command-line tool.
