### ISSUE TITLE
Crash (or wrong results) for unusual execution-time probability distribution

### ISSUE THREAD

**Issue by sharkdp** [Gabriel439/bench#21]
First off, thank you very much for `bench`! It's a fantastic tool.

I've been working on a similar tool and I'm in the progress of writing a few tests. I was wondering what would happen if the probability distribution (for the execution time) had unusual properties (non-Gaussian). I wrote this program which sleeps either 0 or 2 seconds:
```
> cat sleep-0-or-2.sh 
#!/bin/bash

sleep "$(( (RANDOM % 2) * 2 ))"
```

The mean time should be 1 s and the standard deviation should also be 1 s (if my math is correct). To double-check, I also used `bench` to verify. I wasn't expecting this:
```
> bench ./sleep-0-or-2.sh
benchmarking ./sleep-0-or-2.sh
time                 -794.0 ms  (-1.994 s .. NaN s)
                     0.797 R²   (0.661 R² .. 1.000 R²)
mean                 1.009 s    (1.009 s .. 1.009 s)
std dev              0.0 s      (0.0 s .. 0.0 s)
variance introduced by outliers: -9223372036854775808% (severely inflated)
```

So I ran it again. I *definitely* wasn't expecting this:
```
> bench ./sleep-0-or-2.sh
benchmarking ./sleep-0-or-2.sh
time                 1.811 s    (-1.990 s .. 6.010 s)
                     0.603 R²   (0.336 R² .. 1.000 R²)
bench: ./Data/Vector/Generic.hs:245 ((!)): index out of bounds (-9223372036854775808,1000)
CallStack (from HasCallStack):
  error, called at ./Data/Vector/Internal/Check.hs:87:5 in vector-0.12.0.1-692PQMDMB6pIQ1uGwefDcQ:Data.Vector.Internal.Check
bench: thread blocked indefinitely in an MVar operation
```

**Comment by Gabriel439** [comment]
You should report this upstream to the `criterion` library since it's unlikely to be a bug in `bench` (which just provides a very thin command-line wrapper around `criterion`), unless it is due to `bench` depending on the wrong version of some dependency

**Comment by sharkdp** [comment]
Ah, right. It looks like this has been reported already: https://github.com/bos/criterion/issues/162

Feel free to close this, unless you want to keep it as a reminder.

**Comment by Gabriel439** [comment]
I'll keep it open for now since I'll need to add a lower bound on `criterion` when the upstream issue is fixed

**Comment by sharkdp** [comment]
Thanks!

**Comment by Gabriel439** [comment]
You're welcome!
