### ISSUE TITLE
bench: TemplateNotFound "default" on macos 10.13.6 with bench 1.0.11

### ISSUE THREAD

**Issue by genevera** [Gabriel439/bench#33]
Looks like #12 is back...

```[bash]
\~ via 🐍 2.7.13
➜ sw_vers -productVersion; bench --version; bench 'sleep .0001' --output sleep.html
10.13.6
bench version 1.0.11
benchmarking sleep .0001
time                 2.743 ms   (2.712 ms .. 2.768 ms)
                     0.999 R²   (0.997 R² .. 1.000 R²)
mean                 2.772 ms   (2.759 ms .. 2.796 ms)
std dev              55.91 μs   (32.94 μs .. 85.06 μs)

bench: TemplateNotFound "default"
2.44s user 1.96s system 85% cpu 5.137s total

```

I installed `bench` via homebrew.

**Comment by Gabriel439** [comment]
This is an issue with the `brew` build of `bench`.  Specifically, the `bench` package depends on another package named `criterion` that has to be built with the flag `-fembed-data-files` in order for the executable to be relocatable.

Whoever maintains this Brew formula:

https://github.com/Homebrew/homebrew-core/blob/master/Formula/bench.rb

... would need to update that to include the build flag for the `criterion` dependency

**Comment by genevera** [comment]
Thanks!  I'll submit a PR to that repo.
