### ISSUE TITLE
Pre-built binary for OS X missing default template for html output?

### ISSUE THREAD

**Issue by elasticdog** [Gabriel439/bench#7]
Using the pre-built binary release download for OS X, when I try to output to html, I get the following *template not found* error:

```
$ bench 'sleep 0.1' --output example.html
benchmarking sleep 0.1
time                 106.4 ms   (105.2 ms .. 108.0 ms)
                     1.000 R²   (0.999 R² .. 1.000 R²)
mean                 107.4 ms   (106.8 ms .. 108.0 ms)
std dev              941.6 μs   (730.3 μs .. 1.152 ms)

bench: TemplateNotFound "default"
```

This is with bench 1.0.1 built with criterion 1.1.1.0, btw.

**Comment by Gabriel439** [comment]
Thanks for reporting this!  I believe this is due to me `strip`ping the binary before uploading to try to trim down the size.  I uploaded a new binary which behaves correctly

**Comment by biolee** [comment]
bench: TemplateNotFound "default" still happen

**Comment by Gabriel439** [comment]
@biolee Which version of `bench` did you download and which operating system are you using?

**Comment by biolee** [comment]
bench-1.0.2-x64-osx-10.11.zip, mac 10.12.3

**Comment by Gabriel439** [comment]
@biolee Hmmm.  So I'm using OS X 10.11.6 so that might account for the difference.  I'm unable to reproduce the issue on my end using the same release

**Comment by phst** [comment]
This is still happening for me on macOS 10.13.12.

**Comment by Gabriel439** [comment]
@phst: See: https://github.com/Gabriel439/bench/issues/12

**Comment by phst** [comment]
Thanks! I guess the issue is then with Homebrew not shipping 1.0.8 yet.

**Comment by Gabriel439** [comment]
It's not 1.0.8 per se that fixes the problem.  It can be any version as long as it is built against `criterion` with the correct flags.  It's just that 1.0.8 on the [releases page](https://github.com/Gabriel439/bench/releases) was the first release I built correctly
