### ISSUE TITLE
Error when providing multiple commands

### ISSUE THREAD

**Issue by avetisk** [Gabriel439/bench#9]
```shell
$ bench "curl http://localhost"
benchmarking curl http://localhost
time                 13.04 ms   (12.91 ms .. 13.25 ms)
                     0.999 R²   (0.997 R² .. 1.000 R²)
mean                 12.88 ms   (12.80 ms .. 12.99 ms)
std dev              240.9 μs   (167.7 μs .. 352.9 μs)
```

But when I try to benchmark more than one:

```shell
$ bench "curl http://localhost" "curl http://localhost:5432"
Error: none of the specified names matches a benchmark
Run "bench --help" for usage information
```

I have this error with whatever command I try: `bench id ls "sleep 1"` given in example gives the same error.

**Comment by Gabriel439** [comment]
My guess is that you have `bench-1.0.1` installed which is the latest version available on Hackage and the release page of this project.  Benchmarking multiple commands was added in `bench-1.0.2` but I haven't cut a release yet.  If you can verify that's the problem then I'll cut a new release.

**Comment by avetisk** [comment]
Good guess, I'm using the `1.0.1` that I downloaded from the release page (for OSX). Would be great if you could release the new version :)

**Comment by Gabriel439** [comment]
Alright, the latest version is available for download [here](https://github.com/Gabriel439/bench/releases/tag/1.0.2)

**Comment by avetisk** [comment]
Works like a charm, thanks!

**Comment by Gabriel439** [comment]
You're welcome! :)
